# This is a sample configuration file for Dowser

output_dir = "./"

[logger]
enabled_transports = "console"
level = "info"

[profiler]
session_id = "" # By default, it will be a random UUID if not provided
enabled_metrics = "memory_usage,time"

[profiler.memory_usage]
enabled_backends = "psutil,resource,tracemalloc,mprof,kernel"
unit = "mb"