# This is a sample configuration file for Dowser

execution_id = ""
output_dir = "./dowser"

[logging]
filename = "dowser.log"
level = "info"
transports = "console,file"
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

[report]
append_timestamp = "true"

[report.metadata]
input = ""

[profiler]
output_dir = "profiler"
enabled_profilers = "time,memory_usage"

[profiler.time.report]
filename = "time"
prefix = ""
suffix = ""

[profiler.memory_usage]
backend = "mprof"
precision = "4"

[profiler.memory_usage.report]
unit = "mb"
filename = "memory-usage"
prefix = ""
suffix = ""
decimal_places = "2"
zfill = "6"
zfill_character = " "

[model.collect]
num_iterations = "5"