# This is a sample configuration file for Dowser

[session]
id = ""
output_dir = "./"

[logger]
enabled_transports = "console,file"
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
level = "info"

[logger.transports.file]
filename = "dowser"
max_bytes = "10485760"
backup_count = "3"
output_dir = ""

[profiler]
enabled_metrics = "memory_usage,time"

[profiler.report]
filename = "profiles"
format = "json"
output_dir = ""

[profiler.metrics.memory_usage]
enabled_backends = "psutil,resource,tracemalloc,mprof,kernel"
precision = "4"
unit = "mb"