# This is a sample configuration file for Dowser

execution_id = ""
output_dir = "./"

[logging]
filename = "dowser.log"
level = "info"
transports = "console,file"
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

[input]
metadata = ""

[profiler]
output_dir = "profiler"
enabled_profilers = "execution_time,memory_usage"

[profiler.execution_time]
output_dir = "execution_time"

[profiler.memory_usage]
output_dir = "memory_usage"
backend = "kernel"
precision = "4"
filename_prefix = ""
filename_suffix = ""
unit = "kb"